apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario-app
  template:
    metadata:
      labels:
        app: supermario-app
    spec:
      containers:
      - name: supermario
        image: medaminehlali/gitops-sonarqube-aks-pipeline:14
        ports:
        - containerPort: 8080